# --- Development Profile ---
# Properties for the 'dev' environment

spring:
  application:
    security:
      jwt:
        secret-key: ${JWT_SECRET_KEY}
        expiration: 86400000
        refresh-token:
          expiration: 604800000
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
