# --- Base Configuration ---
# Common properties for all profiles and default profile activation

spring:
  # Activate 'dev' profile by default if no other profile is specified
  profiles:
    active: dev

  application:
    name: ecommerce
    security:
      jwt:
        expiration: 86400000 # 24 hours in milliseconds
        refresh-token:
          expiration: 604800000 # 7 days in milliseconds

  # JPA settings common to all environments
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Common datasource properties
  datasource:
    driver-class-name: org.postgresql.Driver

# Application security configuration
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
